sudo: false
language: python
env:
  - PYTHON_VERSION=3.5
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda3/bin:$PATH
install:
  - conda create --yes -n test-env python=$PYTHON_VERSION nose flake8 'setuptools<20.5.0'
  - source activate test-env
  - pip install .
script:
  # TODO don't require devs to remember setting this env var before running
  # tests
  - __QIIME2_TEST_MODE__=ON nosetests  
  - flake8 qiime setup.py
